[功能] 新建managements app & 增加商品管理功能
astrocamp/16th-CakeCapture pull request #102
Opened 2024-05-31 03:58 UTC by hiw40143113

1. 新建management 後台管理 app
2.  poetry 增加 plotly (畫圖表)
3.  prdoucts models 增加 status 欄位 (需要migration & migrate)
4.  後台進入需superuser，登入後在navbar點選"後台管理"

2024-05-31 19:28 UTC, x10akd approved these changes

2024-06-03 02:50 UTC, cacachang requested changes

2024-06-03 02:50 UTC, cacachang commented on products/models.py
> +    status = models.BooleanField(default=True)
可以用 enum 來處理，如果以後新增狀態就不用再改了

2024-06-03 02:50 UTC, cacachang commented on templates/managements/add_category.html
> +	<h1 class="text-2xl font-bold border-b-2 border-red-300">新增類別</h1>
縮排 ～“～ 不要再讓我看到第二次

2024-06-03 02:50 UTC, cacachang commented on products/migrations/0003_product_status.py
> +    dependencies = [
是說我拉下來的時候為什麼沒有 migration 002

2024-06-03 05:25 UTC, chienchuanw approved these changes

2024-06-03 05:45 UTC, chienchuanw approved these changes

2024-06-03 05:45 UTC, merged