Lan
astrocamp/16th-CakeCapture pull request #12
Opened 2024-05-07 05:03 UTC by bb84729

add login and register

2024-05-07 05:15 UTC, chienchuanw approved these changes
除非是完全新的檔案，不然有些現有的內容，像是 settings.py 盡量不要全部覆蓋，有可能會動到本來的設定。
像 STATICFILES_DIRS 就被蓋掉了，我之後再加回來。

2024-05-07 05:32 UTC, x10akd requested changes
不用把快取上傳

2024-05-07 05:45 UTC, chienchuanw approved these changes

2024-05-07 05:45 UTC, x10akd approved these changes

2024-05-07 05:47 UTC, eugeniekaow approved these changes

2024-05-07 05:48 UTC, hiw40143113 approved these changes

2024-05-07 05:55 UTC, NoraSeirei approved these changes
Brilliant

2024-05-07 05:55 UTC, merged

2024-05-14 16:46 UTC, cacachang commented on accounts/forms.py
> +    password1 = forms.CharField(
不要用 password1 來命名，用 `password` 就好

2024-05-14 16:46 UTC, cacachang commented on accounts/forms.py
> +    password2 = forms.CharField(
同上，可以用 `password_confirmation` 之類的來命名

2024-05-14 16:46 UTC, cacachang commented on accounts/urls.py
> +
不要的空白就刪掉

2024-05-14 16:46 UTC, cacachang commented on accounts/views.py
> +# 註冊
方法名稱都已經足以辨識出來的話，其實不需要多放註解

2024-05-14 16:46 UTC, cacachang commented on accounts/views.py
> +#登入
同上