[issu#87]Rwd
astrocamp/16th-CakeCapture pull request #122
Opened 2024-06-05 10:41 UTC by bb84729

1. 添加各頁面rwd
2. 更改navbar購物車數量顯示

2024-06-06 04:50 UTC, chienchuanw commented
1. 商品頁面裡的類別，是不是有更好的處理方式？現在感覺佔據太多空間
![Screenshot 2024-06-06 at 12 49 06 PM](https://github.com/astrocamp/16th-CakeCapture/assets/45137950/d7ef0c84-8a34-4207-8d9d-ef8ac78c8d25)

2024-06-06 04:53 UTC, chienchuanw commented on templates/shared/nav.html
> +      // 获取购物车数量的元素
這一區的簡體字 😵‍💫

2024-06-06 04:55 UTC, chienchuanw commented on templates/shared/nav.html
> -        <div class="absolute bg-white text-grey rounded-lg mt-1 py-1 w-36  z-20" x-cloak x-show="show">
這邊的 `x-cloak` 應該不能拔，拔掉的話，每次頁面載入時，下拉選單都會閃現一下

2024-06-06 04:57 UTC, chienchuanw requested changes
1. 註解中使用到簡體字的部分要注意
2. templates/products/detail.html 的 review 評論區塊，縮排變成四格了，要調整成兩格

2024-06-10 03:41 UTC, chienchuanw approved these changes

2024-06-10 03:55 UTC, x10akd approved these changes

2024-06-10 03:55 UTC, x10akd commented on templates/shared/nav.html
> +        <div class="relative" x-data="{ show: false }" @click.away="show = false">
商品的 hover 請加在這個 div 
加在 buttom 上, 上下效果不一致

2024-06-10 03:55 UTC, x10akd commented on core/settings.py
> +ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0772-123-192-216-136.ngrok-free.app"]
這個要改成環境變數～

2024-06-10 03:55 UTC, x10akd commented on templates/cart/cart_summary.html
這個是錯誤的檔案, 可以不必留

2024-06-10 03:55 UTC, x10akd commented on templates/carts/cart_summary.html
> +    <p>親愛的會員 ID 您好</p>
{{ user.username }}  這個要加回來

2024-06-10 03:56 UTC, merged