[Issue#69] 修改 coupon 模型並完成在後台頁面的 CRUD
astrocamp/16th-CakeCapture pull request #123
Opened 2024-06-05 14:01 UTC by chienchuanw

2024-06-06 02:12 UTC, cacachang commented
這 PR 為什麼沒有說明

2024-06-06 02:44 UTC, cacachang requested changes

2024-06-06 02:44 UTC, cacachang commented on accounts/signals.py
> +
所以新用戶還是會有 coupon ?

2024-06-06 02:45 UTC, cacachang commented
前台的 coupon 使用邏輯在哪裡

2024-06-06 02:59 UTC, chienchuanw commented
補充說明
1. accounts/models.py 新增 `UserCoupon` 紀錄 `Profile` 與 `Coupon` 的關係表格
2. accounts/signals.py 新增 `create_coupon_for_new_user` 功能，當有新的使用者註冊時，後台會自動生成一張 5XCAMP 優惠券，並分配給使用者，該優惠券也會被存入 `Coupon` table 裡。
3. app `managements` 中，新增 `coupon_list` 與 `add_coupon` 功能，可以於後台管理查看、編輯、新增優惠券
4. 前台使用優惠券的欄位尚未做完

![Screenshot 2024-06-06 at 10 52 19 AM](https://github.com/astrocamp/16th-CakeCapture/assets/45137950/7a5463da-6e72-4020-a76e-80e80298bb13)

2024-06-06 02:59 UTC, chienchuanw commented
> 這 PR 為什麼沒有說明

2024-06-06 03:01 UTC, chienchuanw commented on accounts/signals.py
> +
有的，新用戶在註冊時會得到一張 `5XCAMP` 折價券
寫在 accounts/signals.py 的 `create_coupon_for_new_user` 的函式裡

2024-06-06 03:06 UTC, chienchuanw commented
補充說明
1. orders/order_confirm 的頁面，將郵資改為 70，且可以加總至種購買金額裡。
2. 新增優惠券輸入欄位（功能尚未完成）。

![Screenshot 2024-06-06 at 11 04 12 AM](https://github.com/astrocamp/16th-CakeCapture/assets/45137950/8121ae13-27f5-4e8b-8d42-8ed8a88ce4ca)

2024-06-06 15:55 UTC, chienchuanw commented
1. 增加優惠券刪除功能

![Screenshot 2024-06-06 at 11 54 31 PM](https://github.com/astrocamp/16th-CakeCapture/assets/45137950/6daafd72-2d5e-42e9-8be9-8d700b651586)

2024-06-07 03:52 UTC, chienchuanw commented
6/7 新增事項
1. 將頁面「使用者資訊」中的子頁面切分出去，使用 include 神社語法囊括進來
2. 將「退貨須知」勾選欄位，改為必填 `required`。

2024-06-07 04:21 UTC, x10akd approved these changes

2024-06-07 04:32 UTC, chienchuanw commented
6/7 新增事項
1. 頁面「使用者資訊 - 優惠券」可渲染使用者目前所擁有的 coupon 資訊
2. 修改頁面「使用者資訊」上方頁籤名稱

<img width="1440" alt="Screenshot 2024-06-07 at 12 30 04 PM" src="https://github.com/astrocamp/16th-CakeCapture/assets/45137950/26403351-797e-4ee2-bc41-6f8bd48f5075">

2024-06-07 06:22 UTC, eugeniekaow approved these changes

2024-06-07 06:31 UTC, merged