新增about頁面
astrocamp/16th-CakeCapture pull request #17
Opened 2024-05-08 07:57 UTC by eugeniekaow

新增about.html
新增about.css

2024-05-08 07:58 UTC, x10akd approved these changes

2024-05-08 07:59 UTC, bb84729 approved these changes

2024-05-08 08:04 UTC, NoraSeirei approved these changes

2024-05-08 08:09 UTC, hiw40143113 approved these changes

2024-05-08 08:13 UTC, chienchuanw requested changes
about 頁面上方的 margin 看起來不夠
base.html 的 block content 與 endblock 因為格式化，讓網站失效了。

2024-05-08 08:55 UTC, chienchuanw approved these changes

2024-05-08 09:15 UTC, merged

2024-05-14 18:02 UTC, cacachang commented on templates/pages/home.html
>  <script>
包去 JS 裡面