新增 user 頁面
astrocamp/16th-CakeCapture pull request #29
Opened 2024-05-10 04:48 UTC by x10akd

1. 新增 user 頁面

此頁面需要帶入使用者 ID 為網址, 目前未有使用者編號, 故測試網址為 /accounts/user

2024-05-10 05:13 UTC, chienchuanw commented
看看版位這樣調整會不會比較好呢？
<img width="1262" alt="Screenshot 2024-05-10 at 1 06 08 PM" src="https://github.com/astrocamp/16th-CakeCapture/assets/45137950/943b0244-f618-45ac-a2c3-11ee7ff7d635">

2024-05-10 05:26 UTC, chienchuanw commented on templates/accounts/user.html
> +{% extends 'shared/base.html' %} {% block content%}
{% block content %}
記得換行，不要跟 extends 連在一起，content 後面要空一格

2024-05-10 05:27 UTC, chienchuanw commented on templates/accounts/user.html
> +{% endblock%}
endblock 後面要空一格

2024-05-10 05:28 UTC, chienchuanw commented on .gitignore
> -*/__pycache__
改這樣有什麼差別嗎？

2024-05-10 06:05 UTC, hiw40143113 approved these changes

2024-05-10 07:55 UTC, bb84729 approved these changes

2024-05-10 07:55 UTC, bb84729 commented on templates/accounts/user.html
> +  href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css"
tailwind和alpine在base有cdn進來了

2024-05-10 08:13 UTC, NoraSeirei approved these changes

2024-05-10 08:52 UTC, eugeniekaow requested changes

2024-05-10 08:52 UTC, eugeniekaow commented on templates/accounts/user.html
> +                href="#"
請注意縮排有問題

2024-05-10 09:55 UTC, eugeniekaow approved these changes

2024-05-10 10:42 UTC, chienchuanw approved these changes

2024-05-10 10:42 UTC, merged

2024-05-14 18:24 UTC, cacachang commented on templates/accounts/user.html
> +            <!-- <div class="hidden md:block"> -->
沒用到就拿掉