增加排序功能
astrocamp/16th-CakeCapture pull request #50
Opened 2024-05-13 10:01 UTC by hiw40143113

商品列表頁(所有商品/類別/搜尋)增加排序功能

2024-05-13 14:15 UTC, bb84729 approved these changes

2024-05-13 14:18 UTC, eugeniekaow approved these changes

2024-05-13 17:22 UTC, NoraSeirei approved these changes

2024-05-14 05:00 UTC, hiw40143113 commented
更改成模組化html並添加註解

2024-05-14 08:56 UTC, x10akd approved these changes

2024-05-15 04:26 UTC, chienchuanw requested changes
排序功能失效了

2024-05-15 04:31 UTC, hiw40143113 commented
已修復

2024-05-15 05:56 UTC, chienchuanw approved these changes

2024-05-15 05:56 UTC, merged