[Issue#41] 新增聊天室頁面與樣式
astrocamp/16th-CakeCapture pull request #67
Opened 2024-05-17 14:55 UTC by chienchuanw

1. 使用 tailwindcss CDN 製作聊天室樣式
（目前不知道為什麼，用專案裡的 tailwindcss 會掉樣式）

![Screenshot 2024-05-17 at 10 54 51 PM](https://github.com/astrocamp/16th-CakeCapture/assets/45137950/28fb207b-e255-4ebd-8423-0348066bc860)

2024-05-20 06:48 UTC, bb84729 approved these changes

2024-05-20 11:40 UTC, chienchuanw commented
1. 完成 websocket 串接，且可以連線對話

2024-05-20 11:48 UTC, chienchuanw commented
有新增 channels 與 htmx 套件，記得 `$ poetry install`

2024-05-21 02:46 UTC, cacachang requested changes

2024-05-21 02:46 UTC, cacachang commented on core/settings.py
> +ALLOWED_HOSTS = ["localhost", "127.0.0.1", "*"]
加星號的用意是什麼？

2024-05-21 02:46 UTC, cacachang commented on templates/chats/chatroom.html
> +	<wrapper class="block max-w-2xl mx-auto mt-40 mb-20 px-6">
這檔案的縮排要改

2024-05-21 02:46 UTC, cacachang commented on templates/chats/chatroom_msg.html
> +	<div class="bg-red-200 rounded-l-lg rounded-tr-lg p-4 max-w-[75%]">
同上

2024-05-21 02:46 UTC, cacachang commented on templates/chats/chatroom_msg_partial.html
> +	<style>
同上

2024-05-21 02:49 UTC, chienchuanw commented on templates/chats/chatroom.html
> +	<wrapper class="block max-w-2xl mx-auto mt-40 mb-20 px-6">
但我電腦裡的縮排都是 2 格耶
<img width="978" alt="Screenshot 2024-05-21 at 10 48 07 AM" src="https://github.com/astrocamp/16th-CakeCapture/assets/45137950/f8d796fb-3836-40c9-9481-2eb161caed3e">

2024-05-21 02:49 UTC, chienchuanw commented on templates/chats/chatroom_msg.html
> +	<div class="bg-red-200 rounded-l-lg rounded-tr-lg p-4 max-w-[75%]">
<img width="913" alt="Screenshot 2024-05-21 at 10 48 16 AM" src="https://github.com/astrocamp/16th-CakeCapture/assets/45137950/129e7cdc-b5a2-4cd5-a435-6ddf8b8b63de">

2024-05-21 02:50 UTC, chienchuanw commented on templates/chats/chatroom_msg_partial.html
> +	<style>
<img width="469" alt="Screenshot 2024-05-21 at 10 48 22 AM" src="https://github.com/astrocamp/16th-CakeCapture/assets/45137950/e1f13966-b88e-42ec-9cef-ce03689d361f">

2024-05-21 03:34 UTC, chienchuanw commented
注意須知
1. 有安裝新的套件，記得 `$ poetry install`
2. 記得 migrations / migrate
3. 由於此分支的登入系統壞掉了，要用 127.0.0.1:8000/admin 進到後台登入
4. 在後台 chat group 新增一個名為 public-chat 的聊天室
5. 在後台 group message 新增聊天室的使用者與對話內容
6. 可以再用無痕瀏覽另外開一個使用者，自己與自己對話

2024-05-21 08:21 UTC, chienchuanw commented on core/settings.py
> +ALLOWED_HOSTS = ["localhost", "127.0.0.1", "*"]
`*` 代表就算不是 localhost 或 127.0.0.1 也都還是可以連線
https://docs.djangoproject.com/en/5.0/ref/settings/#allowed-hosts

2024-05-22 02:44 UTC, cacachang requested changes

2024-05-22 02:44 UTC, cacachang commented on templates/chats/chatroom_msg.html
> +			<!-- 到時候下方的 a href 要連到會員資料頁面 -->
在 HTML 能不放就不放，前台檢查都看得到

2024-05-22 02:44 UTC, cacachang commented on templates/chats/chatroom.html
> +<style>
把他放到 css 檔裡面 或者用 tailwind 解決掉

2024-05-22 02:44 UTC, cacachang commented on chats/routing.py
> +    path("ws/chatroom/<chatroom_name>", ChatroomConsumer.as_asgi()),
ws 可以拿掉

2024-05-22 02:44 UTC, cacachang commented on core/settings.py
> +# WSGI_APPLICATION = "core.wsgi.application"
為什麼要註解這個？如果確定要用 ASGI 的方式就可以刪掉了

2024-05-22 07:49 UTC, x10akd approved these changes

2024-05-22 09:01 UTC, hiw40143113 approved these changes

2024-05-22 09:01 UTC, merged