[Issue#70] 整理並更新 settings.py / README.md / 資料庫 / pyproject.toml 等檔案
astrocamp/16th-CakeCapture pull request #73
Opened 2024-05-21 07:18 UTC by chienchuanw

1. 將第三方登入金鑰從資料庫中移除，並改為使用環境變數（金鑰用 discord 傳給大家）
2. 更新資料庫為 mock_date_0521 並存放在 mock_data 資料夾
3. 刪除 settings.py 多餘的程式碼與空行
4. (WIP) 更新 README.md 並新增團隊成員名單
5. 更新 pyproject.toml 中的 authors 欄位
6. 移除 tailwindcss.config.js 中 safelist 的註解原始碼

2024-05-22 02:17 UTC, cacachang requested changes

2024-05-22 02:17 UTC, cacachang commented on core/settings.py
> +    # allauth-related
這應該也不用

2024-05-22 02:17 UTC, cacachang commented on core/settings.py
> +    # User-defined apps
同上

2024-05-22 02:17 UTC, cacachang commented on core/settings.py
> +    "allauth.socialaccount.providers.facebook",
有確定要用 Facebook 登入嗎？沒有就拔掉

2024-05-22 02:17 UTC, cacachang commented on core/settings.py
> +    # allauth-related
可拿掉

2024-05-22 02:17 UTC, cacachang commented on core/settings.py
> +                # carts-related
拿

2024-05-22 02:17 UTC, cacachang commented on core/settings.py
> +    # allauth-related
可拿掉，這些官方文件都有寫，不需要註解

2024-05-22 02:17 UTC, cacachang commented on pages/urls.py
> +    path("cart/confirm", views.cart_confirm, name="cart_confirm"),
為什麼這邊加回來了

2024-05-22 04:11 UTC, chienchuanw commented on core/settings.py
> +    # allauth-related
已移除

2024-05-22 04:11 UTC, chienchuanw commented on core/settings.py
> +    # User-defined apps
已移除

2024-05-22 04:11 UTC, chienchuanw commented on core/settings.py
> +    "allauth.socialaccount.providers.facebook",
已移除

2024-05-22 04:12 UTC, chienchuanw commented on core/settings.py
> +    # allauth-related
已移除

2024-05-22 04:12 UTC, chienchuanw commented on core/settings.py
> +                # carts-related
已移除

2024-05-22 04:12 UTC, chienchuanw commented on pages/urls.py
> +    path("cart/confirm", views.cart_confirm, name="cart_confirm"),
已移除

2024-05-22 04:12 UTC, chienchuanw commented on core/settings.py
> +    # allauth-related
已移除

2024-05-22 06:23 UTC, hiw40143113 approved these changes

2024-05-22 15:08 UTC, x10akd approved these changes

2024-05-22 15:08 UTC, x10akd commented on core/settings.py
>  SECRET_KEY = "django-insecure-y1gkrdf9wpvr#^l$^-6nx7sf2h+y-t58y_nhfs@3c6$a+!#&la"
這個是不是也要用成環境變數會比較好？

2024-05-22 15:08 UTC, x10akd commented on core/settings.py
>  EMAIL_PORT = 587
此處也需要改持環境變數

2024-05-23 03:58 UTC, chienchuanw commented on core/settings.py
>  SECRET_KEY = "django-insecure-y1gkrdf9wpvr#^l$^-6nx7sf2h+y-t58y_nhfs@3c6$a+!#&la"
改嚕！

2024-05-23 03:59 UTC, chienchuanw commented on core/settings.py
>  EMAIL_PORT = 587
也改嚕！

2024-05-23 04:02 UTC, eugeniekaow approved these changes

2024-05-23 04:02 UTC, merged