[Issue#50-2] add review-edit and load-more-reviews function and modify sort function
astrocamp/16th-CakeCapture pull request #76
Opened 2024-05-22 10:55 UTC by hiw40143113

1. 增加評論編輯及載入更多功能
2. 增加評價排序功能及修正部分bug

2024-05-22 16:00 UTC, x10akd commented on store/views.py
> -# 因需要category值，用cat變數來接
這行可能需要留下, 不然單純看到 cat 會一時反應不過來

2024-05-22 16:48 UTC, x10akd approved these changes

2024-05-23 09:11 UTC, bb84729 approved these changes

2024-05-24 02:56 UTC, cacachang requested changes

2024-05-24 02:56 UTC, cacachang commented on core/settings.py
> +            # "service": "my_service",
這邊好像講了很久要刪掉，但為什麼到現在都還沒刪？

2024-05-24 02:56 UTC, cacachang commented on store/urls.py
> +    path(
命名什麼時候會改掉？

2024-05-24 02:56 UTC, cacachang commented on store/views.py
>      elif sort_by == "ph2l":  # ph2l = price high to low
如果你的命名寫得好懂一點，那就不需要註解了不是嗎

2024-05-24 02:56 UTC, cacachang commented on store/views.py
> +            .annotate(
兩個 `annotate` 是否可以合在一起

2024-05-24 02:56 UTC, cacachang commented on store/views.py
> +    p = Paginator(products, 9)
已提過，命名

2024-05-24 02:56 UTC, cacachang commented on store/views.py
> -# 因需要category值，用cat變數來接
所以說為什麼要用 `cat`

2024-05-24 02:56 UTC, cacachang commented on store/views.py
> +                    "bool": True,
這個 bool 代表什麼意思？

2024-05-24 03:20 UTC, chienchuanw commented on core/settings.py
> +            # "service": "my_service",
dev 裡面應該是沒有的
<img width="683" alt="Screenshot 2024-05-24 at 11 20 20 AM" src="https://github.com/astrocamp/16th-CakeCapture/assets/45137950/a51d0bf6-ba29-42c1-9a94-41e3428f4fa5">

2024-05-24 03:23 UTC, chienchuanw commented on store/views.py
>      elif sort_by == "ph2l":  # ph2l = price high to low
@hiw40143113 
看要不要改成 `price_low_high` 
反之亦然

2024-05-24 03:26 UTC, chienchuanw commented on store/views.py
> +                    "bool": True,
`cat` 看要不要改 `categ` 或是直接寫全名也可以？

2024-05-24 03:28 UTC, chienchuanw commented on store/views.py
>      elif sort_by == "ph2l":  # ph2l = price high to low
這邊是 GPT 推薦的一些命名
```python
price_ascending
price_low_to_high
price_asc
sorted_by_price_asc
price_order_asc
```

2024-05-25 01:58 UTC, chienchuanw approved these changes

2024-05-25 01:59 UTC, merged