[Issue#77] 增加 LINE Chatbot 功能
astrocamp/16th-CakeCapture pull request #78
Opened 2024-05-23 06:44 UTC by chienchuanw

Requirement: 
1. `$ poetry install`
2. 去 [LINE Developers](https://developers.line.biz/en/) > Console 創建 Providers
3. 在 LINE Developers 創建 Messaging API，接續複製 Channel secret 到專案 .env 的 `LINE_CHANNEL_SECRET`，複製 Messaging API 分頁中的 Channel access token （要點 issue 創建） 到 .env 的 LINE_ACCESS_TOKEN
4. 到 [ngrok](https://ngrok.com/) 申請帳號，並依官方引導完成安裝與金鑰註冊
5. 在本機 terminal 使用 `$ ngrok http <localhost port>` e.g `$ ngrok http 8000`
6. 複製 ngrok 的提供的網址至 settings.py 中的 `ngork_url` 中，記得不要複製到 https://
7. 啟動本機 Server `$ python manage.py runserver`
8. 再次複製 ngrok 提供的網址（包含 https://）
9. 到 LINE Developers 的 Messaging API 分頁中的 Webhook settings 區塊，在 Webhook URL 貼上 ngrok 網址並在後方加上 /chats/callback
10. 點選 Verify 完成驗證後，開啟下方 Use webhook 功能
11. 用手機掃描分頁上方的 QR code 即可開始測試

2024-05-24 02:33 UTC, cacachang requested changes

2024-05-24 02:33 UTC, cacachang commented on chats/urls.py
> +    path("callback", callback, name="callback"),
可以換個名字，這樣看不懂是要做什麼的

2024-05-24 02:33 UTC, cacachang commented on core/settings.py
> +ALLOWED_HOSTS = ["localhost", "127.0.0.1", ngork_url]
ngrok_url 應該可以直接改環境變數，上面就不需要那一行了

2024-05-24 03:00 UTC, chienchuanw commented on core/settings.py
> +ALLOWED_HOSTS = ["localhost", "127.0.0.1", ngork_url]
已修改

2024-05-24 03:00 UTC, chienchuanw commented on chats/urls.py
> +    path("callback", callback, name="callback"),
已改為 `line_callback`

2024-05-26 06:40 UTC, hiw40143113 approved these changes

2024-05-28 06:06 UTC, eugeniekaow commented
有衝突

2024-05-30 04:23 UTC, x10akd approved these changes

2024-05-30 04:24 UTC, x10akd commented
poetry.lock 使用 $poetry lock 就可以更新 lock 檔, 之後便可執行 install, 後續測試正常

2024-05-30 06:29 UTC, bb84729 approved these changes

2024-06-02 03:34 UTC, merged