[Issue#74] 增加我的最愛功能
astrocamp/16th-CakeCapture pull request #89
Opened 2024-05-26 14:40 UTC by bb84729

增加我的最愛功能
可添加，刪除

2024-05-28 02:14 UTC, cacachang requested changes

2024-05-28 02:14 UTC, cacachang commented on accounts/views.py
> +<<<<<<< HEAD
到現在還出現衝突，不太對吧

2024-05-28 05:11 UTC, bb84729 commented on accounts/views.py
> +<<<<<<< HEAD
已解決

2024-05-28 10:41 UTC, chienchuanw approved these changes

2024-05-30 02:50 UTC, cacachang requested changes

2024-05-30 02:50 UTC, cacachang commented on accounts/views.py
> +from carts.cart import Cart
上面有 import 全部了，下面應該不需要再 import ?

2024-05-30 02:50 UTC, cacachang commented on accounts/views.py
> +    print("=" * 100)
push 上來以前要把這些 debug 的東西刪掉

2024-05-30 02:50 UTC, cacachang commented on accounts/views.py
> +    return JsonResponse({"error": "Invalid request"}, status=400)
這邊應該不是我可以刪除的，就渲染沒有權限的訊息？
現在變成判斷 method 不是 Post 就回給他 400

2024-05-30 02:50 UTC, cacachang commented on order/views.py
> +from .models import OrderMethod,Order,OrderItem
這邊不用刪掉空格吧

2024-05-30 02:50 UTC, cacachang commented on products/admin.py
> +from .models import Category, Product, ProductReview,Favorite
加空格，養成好習慣跟著 coding style

2024-05-30 02:50 UTC, cacachang commented on products/models.py
> +    # def average_rating(self):
這註解還有要用到嗎？

2024-05-30 02:50 UTC, cacachang commented on templates/products/products_base.html
> +  $(document).ready(function ()
打算繼續把 js 放在 html 裡面嗎？

2024-05-30 02:50 UTC, cacachang commented on templates/products/product_detail.html
> +	<section class="product-photo flex p-10">
縮排！

2024-05-30 02:50 UTC, cacachang commented on templates/cart/cart_list.html
> +
已經開發專案這麼久了，縮排這種失誤就不能再犯了吧？

2024-05-30 03:48 UTC, x10akd commented
拉下來使用
1. 無法進到購物車頁面會出現 沒有 store 的命名空間, 我確認過 urls 內有設置, 但此故障我無法排除後測試, 再麻煩確認一下
2. 在詳情頁面內無法新增
<img width="928" alt="截圖 2024-05-30 上午11 47 30" src="https://github.com/astrocamp/16th-CakeCapture/assets/138242581/1119505c-d435-4528-9a2d-7d1b7c9fb67d">

2024-05-30 07:00 UTC, x10akd approved these changes
以確認可修改的物件以修改, 移出JS與詳情頁加入最愛 已開票待處理

2024-05-30 07:02 UTC, hiw40143113 approved these changes

2024-05-30 07:04 UTC, merged