增加常見問題頁面
astrocamp/16th-CakeCapture pull request #93
Opened 2024-05-27 07:39 UTC by eugeniekaow

![螢幕擷取畫面 2024-05-27 153818](https://github.com/astrocamp/16th-CakeCapture/assets/70026173/729cac01-1336-47c9-9870-631ac3fbc837)

2024-05-28 02:17 UTC, cacachang requested changes

2024-05-28 02:17 UTC, cacachang commented on pages/urls.py
> +    path("common/",views.common,name="common"),
為什麼這路徑要叫 common ?

2024-05-28 02:23 UTC, eugeniekaow commented on pages/urls.py
> +    path("common/",views.common,name="common"),
常見問題的常見common

2024-05-28 05:12 UTC, bb84729 approved these changes

2024-05-28 05:57 UTC, eugeniekaow commented
更新:關於我們和改變navbar名字

2024-05-30 02:52 UTC, cacachang requested changes

2024-05-30 02:52 UTC, cacachang commented on messagememos/admin.py
> +# Register your models here.
為什麼會動到這個檔案？

2024-05-30 02:52 UTC, cacachang commented on pages/urls.py
> +    path("common/",views.common,name="common"),
用更容易理解的命名 例如 question 之類的 common 指的是什麼常見？常見的人？常見的書？

2024-05-30 03:19 UTC, eugeniekaow commented on messagememos/admin.py
> +# Register your models here.
因為資料庫有問題，刪掉過後再migrations

2024-05-30 04:01 UTC, eugeniekaow commented on pages/urls.py
> +    path("common/",views.common,name="common"),
已修改為common_problem

2024-05-30 04:33 UTC, eugeniekaow commented
修改路徑名稱原本common/改成common_problem
在關於我們的頁面添加RWD

2024-06-01 07:56 UTC, x10akd approved these changes

2024-06-02 03:49 UTC, chienchuanw commented on pages/urls.py
> +    path("common_problem/",views.common_problem,name="common_problem"),
是不是考慮改成 problems 或 questions 就好，網址可以更簡潔一點。

2024-06-02 03:50 UTC, chienchuanw commented on pages/views.py
> +def common_problem(request):
同上

2024-06-02 03:57 UTC, chienchuanw requested changes
1. 是否考慮直接將「常見問題」連結新增在 navbar？（如下圖標示）
2. 另外如有要修改 common_problem 名稱， 記得連同 html 檔名也一同修改
3. 記得解衝突

![Screenshot 2024-06-02 at 11 55 34 AM](https://github.com/astrocamp/16th-CakeCapture/assets/45137950/ce3fbab1-a6a9-4a45-84d6-fdde649132ee)

2024-06-03 04:29 UTC, chienchuanw approved these changes

2024-06-03 04:29 UTC, merged