更新庫存及添加加購商品
astrocamp/16th-CakeCapture pull request #98
Opened 2024-05-29 06:46 UTC by bb84729

1. 產品在結帳完成後會扣掉庫存
2. 在商品詳細頁面添加加購商品的部分
3. 在category新增一個類別 upsell

2024-05-30 12:29 UTC, x10akd commented on order/views.py
這邊一大串註解跟下面一樣, 如果功用一樣就把這個刪掉吧

2024-06-01 16:47 UTC, x10akd approved these changes

2024-06-03 02:20 UTC, cacachang requested changes

2024-06-03 02:20 UTC, cacachang commented on templates/cart/cart_summary.html
> +        <div class="flex text-xl font-semibold">
請問縮排是要用兩格還是四格

2024-06-03 02:20 UTC, cacachang commented on templates/products/detail.html
> +	<div class="py-6 flex flex-col items-center">
@x10akd 請問一下為什麼這個縮排這樣 還是 approve?

2024-06-03 03:27 UTC, x10akd commented on templates/products/detail.html
> +	<div class="py-6 flex flex-col items-center">
我這邊看原始碼是正常的

2024-06-03 03:28 UTC, x10akd commented on templates/cart/cart_summary.html
> +        <div class="flex text-xl font-semibold">
html 是兩格, 穿雜在中間沒注意到,  修正後我再重推

2024-06-03 05:07 UTC, chienchuanw approved these changes

2024-06-03 05:07 UTC, merged